### ISSUE TITLE
02 - Ambiente de desenvolvimento

### ISSUE THREAD

**Issue by leohmoraes** [leohmoraes/rocketseat-06#2]
[https://docs.rocketseat.dev/](https://docs.rocketseat.dev/)

- [x] brew install watchman
- [x] npm install -g react-native-cli ou **yarn global add react-native-cli**
- [x] [Instação do SDK od Java](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
- [x] Solucionando problemas

**Comment by leohmoraes** [comment]
````
$ java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

$  ~/Android/Sdk/tools/bin/sdkmanager  "platform-tools" "platforms;android-27" "build-tools;27.0.3;5D"
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more
`````
Delete anything older than Java 8 from **/Library/Java/JavaVirtualMachines** – Dimitris Mar 29 '18 at 16:04

Na pasta **/Library/Java/JavaVirtualMachines** movendo ou excluindo **openjdk-11.0.2.jdk** o erro anterior resolveu....

```` 
$ sudo mv openjdk-11.0.2.jdk /tmp/openjdk-11.0.2.jdk

$ ~/Android/Sdk/tools/bin/sdkmanager  "platform-tools" "platforms;android-27" "build-tools;27.0.3;5D"

Warning: Failed to find package build-tools;27.0.3;5D
````

brew search java
brew search jdk

[Usando o brew para instalar o java](https://www.dev2qa.com/how-to-install-uninstall-multiple-java-versions-in-mac-os-by-home-brew-or-manually/)

criei um arquivo vazio na pasta ~/.android/repositories.cfg

muitos indicaram a instalação do build tools com o Android Studio
brew cask install android-studio
https://www.youtube.com/watch?v=AEWVtB8osY0

**Comment by leohmoraes** [comment]
````
~/Android/Sdk/tools/bin/sdkmanager  "platform-tools" "platforms;android-27" "build-tools;27.0.3"
````
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more

Ao mover ou retirar este arquivo ** /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk**, 
o processo avança mas ainda ocorre um erro:
Warning: File /Users/leo/.android/repositories.cfg could not be loaded.         
Warning: Failed to find package build-tools;27.0.3;5D 
] 10% Computing updates...  
*

Por fim, instalei o Android Studio,

**Comment by leohmoraes** [comment]
Algumas anotações:
Supported commands are:

> android list target
> android list avd
> android list device
> android create avd
> android move avd
> android delete avd
> android list sdk
> android update sdk

**brew cask install android-studio**

**https://docs.rocketseat.dev/ambiente-react-native/android/emulador**

> connect IP_DO_SEU_EMULADOR:5555
> connect 192.168.0.13:5555
> adb devices

Se aparecer o nome do seu dispositivo na lista, seu emulador foi conectado com sucesso!
Com o emulador aberto, basta rodar **react-native run-android** na pasta do seu projeto.

Para testar no iOS, precisa do Xcode instalado e depois executar este comando:
> react-native run-ios --simulator="iPhone XS Max"
